name: Clear Cache

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Clear Cache
      run: rm -rf _site

    - name: Pull ghcr.io/actions/jekyll-build-pages:v1.0.8
      uses: ghcr.io/actions/jekyll-build-pages:v1.0.8

    - name: Build Website
      run: actions/jekyll-build-pages@v1